name: Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Compile
        run: |
          npm install
          npx tsc
      - name: Run main function
        env:
          MAIL_API_KEY: ${{ secrets.MAIL_API_KEY }}
          MAIL_SECRET: ${{ secrets.MAIL_SECRET }}
        run: |
           npm run startApp
