name: Run

on:
  schedule:
    - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Compile
        run: |
          npm install
          npx tsc
      - name: Run main function
        run: |
           npm run startApp


