name: Send EVN Outage Emails

on:
  push:
    branches: [ main ]

jobs:
  download_and_parse_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Download and parse data
        run: npm run downloadAndParseData
      - name: Save output
        id: data
        run: echo "::set-output name=outages::$(cat outages.json)"

  send_emails:
    needs: download_and_parse_data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send emails
        env:
          OUTAGES: ${{ needs.download_and_parse_data.outputs.outages }}
        run: npm run sendEmails